import { db } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

// Safe because tableNames values are compile-time constants in this file
function buildTableArrayLiteral(tableNames: string[]): string {
  return tableNames.map((t) => `'${t}'`).join(", ");
}

const EXPECTED_COLUMNS: Record<string, string[]> = {
  bookings: [
    "id",
    "session_token",
    "status",
    "pass_type",
    "attendee_type",
    "quantity",
    "promo_code",
    "promo_discount_amount",
    "group_discount_amount",
    "subtotal_amount",
    "vat_amount",
    "total_amount",
    "payment_method",
    "manual_entry",
    "registration_source",
    "sponsor_id",
    "stripe_session_id",
    "stripe_payment_intent_id",
    "stripe_invoice_id",
    "stripe_invoice_pdf_url",
    "stripe_invoice_payment_url",
    "order_reference",
    "current_step",
    "billing_name",
    "billing_company",
    "billing_email",
    "billing_address",
    "billing_address_line1",
    "billing_address_line2",
    "billing_town",
    "billing_region",
    "billing_postcode",
    "billing_country",
    "billing_phone",
    "billing_vat_number",
    "invoice_due_date",
    "hear_about_us",
    "management_token",
    "partial_notification_sent",
    "confirmation_email_sent",
    "welcome_emails_sent",
    "community_social_email_sent",
    "organiser_notified",
    "sheets_synced",
    "created_at",
    "updated_at",
  ],
  attendees: [
    "id",
    "booking_id",
    "is_lead",
    "seat_index",
    "first_name",
    "last_name",
    "job_title",
    "company",
    "work_email",
    "phone",
    "dietary_accessibility",
    "community_social_attending",
    "community_social_dietary",
    "notes",
    "is_tbc",
    "gdpr_consent",
    "gdpr_consent_at",
    "lead_sharing_excluded",
    "lead_sharing_notice_at",
    "created_at",
    "updated_at",
  ],
  event_settings: [
    "id",
    "event_name",
    "event_date",
    "event_venue",
    "event_venue_postcode",
    "org_name",
    "org_address",
    "org_website",
    "logo_data_url",
    "from_name",
    "from_email",
    "freeagent_refresh_token",
    "freeagent_access_token",
    "freeagent_token_expires_at",
    "attendee_changes_locked",
    "attendee_changes_locked_message",
    "ref_prefix",
    "ref_offset",
    "notify_complete_subject",
    "notify_incomplete_subject",
    "notify_attendee_subject",
    "event_start_at",
    "event_end_at",
    "event_timezone",
    "event_description",
    "social_enabled",
    "social_name",
    "social_start_at",
    "social_end_at",
    "social_venue",
    "social_description",
    "updated_at",
  ],
  notification_emails: [
    "id",
    "email",
    "label",
    "notify_complete",
    "notify_incomplete",
    "notify_checkout_expired",
    "notify_billing_edit",
    "notify_sponsor_admin",
    "notify_sponsor_passes",
    "notify_sponsor_content",
    "notify_sponsor_deadlines",
    "created_at",
  ],
  pass_config: [
    "pass_type",
    "current_price",
    "original_price",
    "pricing_period_name",
    "benefits",
    "extra_benefits",
    "updated_at",
  ],
  promo_codes: [
    "id",
    "code",
    "discount_type",
    "discount_value",
    "max_uses",
    "used_count",
    "valid_from",
    "valid_until",
    "is_active",
    "applicable_pass_types",
    "description",
    "once_per_customer",
    "min_quantity",
    "max_quantity_per_booking",
    "max_discount_amount",
    "internal_note",
    "created_at",
    "updated_at",
  ],
  activity_log: ["id", "type", "booking_id", "attendee_id", "data", "created_at"],
  email_templates: ["id", "type", "subject", "html_body", "updated_at"],
  discount_tiers: ["id", "pass_type", "min_quantity", "discount_percent", "label"],
  email_logs: [
    "id",
    "booking_id",
    "sponsor_id",
    "recipient",
    "type",
    "status",
    "error_message",
    "sent_at",
  ],
  pass_inventory: ["id", "pass_type", "remaining", "updated_at"],
  booking_documents: [
    "id",
    "booking_id",
    "document_type",
    "filename",
    "content_type",
    "data",
    "created_at",
    "updated_at",
  ],
  sponsors: [
    "id",
    "company",
    "package_label",
    "status",
    "confirmation_date",
    "notes",
    "vip_allocation",
    "vip_max_per_booking",
    "staff_allocation",
    "vip_code_draft",
    "public_code_draft",
    "portal_access_version",
    "required_deliverables",
    "confirmed_at",
    "welcome_email_sent_at",
    "paused_at",
    "cancelled_at",
    "created_at",
    "updated_at",
  ],
  sponsor_contacts: [
    "id",
    "sponsor_id",
    "role",
    "first_name",
    "last_name",
    "job_title",
    "email",
    "phone",
    "is_primary",
    "created_at",
    "updated_at",
  ],
  sponsor_promo_codes: ["id", "sponsor_id", "promo_code_id", "kind", "created_at"],
  sponsor_tasks: [
    "id",
    "sponsor_id",
    "task_key",
    "label",
    "required",
    "due_at",
    "status",
    "completed_at",
    "last_deadline_check_on",
    "created_at",
    "updated_at",
  ],
  sponsor_sessions: [
    "id",
    "sponsor_id",
    "type",
    "entitlement_label",
    "title",
    "description",
    "takeaways",
    "status",
    "headshot_required",
    "takeaways_required",
    "slides_required",
    "feedback",
    "current_revision",
    "submitted_at",
    "approved_at",
    "exported_at",
    "exported_revision",
    "created_at",
    "updated_at",
  ],
  sponsor_session_revisions: ["id", "session_id", "revision", "snapshot", "actor", "created_at"],
  sponsor_presenters: [
    "id",
    "session_id",
    "name",
    "job_title",
    "company",
    "biography",
    "display_order",
    "created_at",
    "updated_at",
  ],
  sponsor_assets: [
    "id",
    "sponsor_id",
    "session_id",
    "presenter_id",
    "category",
    "original_name",
    "mime_type",
    "byte_size",
    "checksum_sha256",
    "storage_key",
    "version",
    "status",
    "replaces_asset_id",
    "uploader_type",
    "uploader_label",
    "archived_at",
    "created_at",
    "updated_at",
  ],
  sponsor_documents: [
    "id",
    "sponsor_id",
    "asset_id",
    "title",
    "required",
    "acknowledgement_version",
    "created_at",
    "updated_at",
  ],
  sponsor_document_acknowledgements: [
    "id",
    "document_id",
    "sponsor_contact_id",
    "version",
    "acknowledged_by",
    "acknowledged_at",
  ],
  sponsor_pass_requests: [
    "id",
    "sponsor_id",
    "requested_vip",
    "requested_staff",
    "message",
    "status",
    "created_at",
    "resolved_at",
  ],
  sponsor_activity: ["id", "sponsor_id", "type", "actor_type", "actor_label", "data", "created_at"],
  sponsor_redemptions: [
    "id",
    "sponsor_id",
    "promo_code_id",
    "booking_id",
    "units",
    "status",
    "reservation_key",
    "reserved_at",
    "released_at",
    "release_reason",
    "notification_sent_at",
    "notification_failed_at",
  ],
  attendee_badges: [
    "id",
    "attendee_id",
    "code",
    "version",
    "active",
    "issued_at",
    "rotated_at",
    "updated_at",
  ],
  sponsor_scanner_devices: [
    "id",
    "sponsor_id",
    "access_version",
    "token_hash",
    "operator_name",
    "user_agent",
    "pack_version",
    "camera_tested",
    "qr_tested",
    "storage_tested",
    "offline_tested",
    "sync_tested",
    "activated_at",
    "last_seen_at",
    "last_synced_at",
    "revoked_at",
    "revoked_reason",
    "updated_at",
  ],
  sponsor_leads: [
    "id",
    "sponsor_id",
    "attendee_id",
    "rating",
    "scan_count",
    "first_scanned_at",
    "last_scanned_at",
    "created_at",
    "updated_at",
  ],
  sponsor_lead_scan_events: [
    "id",
    "lead_id",
    "sponsor_id",
    "attendee_id",
    "scanner_device_id",
    "operator_name",
    "badge_version",
    "source",
    "captured_at",
    "received_at",
  ],
  sponsor_lead_notes: [
    "id",
    "lead_id",
    "scanner_device_id",
    "operator_name",
    "note",
    "rating",
    "created_at",
  ],
};

export async function checkSchemaConsistency(): Promise<boolean> {
  const tableNames = Object.keys(EXPECTED_COLUMNS);

  const arrayLiteral = buildTableArrayLiteral(tableNames);
  const result = await db.execute(
    sql.raw(`
      SELECT table_name, column_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
      AND table_name = ANY(ARRAY[${arrayLiteral}])
    `),
  );

  const existing: Record<string, Set<string>> = {};
  for (const row of result.rows as { table_name: string; column_name: string }[]) {
    if (!existing[row.table_name]) {
      existing[row.table_name] = new Set();
    }
    existing[row.table_name].add(row.column_name);
  }

  const issues: string[] = [];

  for (const [table, expectedCols] of Object.entries(EXPECTED_COLUMNS)) {
    if (!existing[table]) {
      issues.push(`table "${table}" is missing entirely`);
      continue;
    }
    for (const col of expectedCols) {
      if (!existing[table].has(col)) {
        issues.push(`column "${table}.${col}" is missing`);
      }
    }
  }

  if (issues.length > 0) {
    logger.error(
      { issues },
      `Schema check FAILED: ${issues.length} issue(s) — database is out of date. Apply the approved versioned migration before deploying this release.`,
    );
    return false;
  }

  logger.info("Schema check passed — all expected columns are present");
  return true;
}
